# Generated by Django 4.2.9 on 2026-03-04 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('company_size', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField()),
                ('standardized_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('call_triggered', models.BooleanField(default=False)),
                ('call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QALead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('company_size', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form_mode', models.CharField(default='test', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qa_leads',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PostCallSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('request', models.TextField()),
                ('company_size', models.CharField(max_length=50)),
                ('conv_summary', models.TextField(blank=True, null=True)),
                ('service_interest', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('urgency', models.TextField(blank=True, null=True)),
                ('past_experience', models.TextField(blank=True, null=True)),
                ('budget', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('voicemail', 'Voicemail'), ('call_back', 'Call Back'), ('incorrect_phone', 'Incorrect Phone'), ('failed', 'Failed')], default='complete', max_length=20)),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_summary', to='leads.productionlead')),
            ],
            options={
                'db_table': 'post_call_summaries',
                'ordering': ['-date'],
            },
        ),
    ]
