# Generated by Django 4.2.26 on 2026-03-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcallsummary',
            name='call_type',
            field=models.CharField(default='outbound', max_length=10),
        ),
        migrations.AddField(
            model_name='productionlead',
            name='call_type',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10),
        ),
    ]
