# Generated by Django 4.2.26 on 2026-03-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_postcallsummary_call_type_productionlead_call_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlead',
            name='call_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('forwarding', 'Forwarding'), ('ended', 'Ended')], default='pending', max_length=20),
        ),
    ]
