# Generated by Django 4.2.9 on 2026-03-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_productionlead_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlead',
            name='call_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
