# Generated by Django 4.2.9 on 2026-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_productionlead_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcallsummary',
            name='caller_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postcallsummary',
            name='caller_company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postcallsummary',
            name='caller_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='postcallsummary',
            name='caller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postcallsummary',
            name='caller_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
