# Generated by Django 4.2.9 on 2026-03-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_postcallsummary_caller_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcallsummary',
            old_name='budget',
            new_name='conversation_summary',
        ),
        migrations.RenameField(
            model_name='postcallsummary',
            old_name='past_experience',
            new_name='follow_up_email',
        ),
    ]
